name: Variables
on: 
  workflow_dispatch:
env:
  DEVOPS_HORIZON: "${{ secrets.DEVOPS_HORIZON }}"
jobs:
  print-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Print DEVOPS_HORIZON variable
        run: echo "The value of DEVOPS_HORIZON is:" $DEVOPS_HORIZON"